framework:
    #esi:             ~
    secret:          "%env(APP_SECRET)%"
    form:            ~
    csrf_protection: ~
    trusted_hosts:   ~
    session:
        cookie_lifetime: 605080
        gc_maxlifetime: 252000
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

