security:
  providers:
    users:
      entity:
        class: 'App\Entity\User'
        property: 'usernameCanonical'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: .*
      context: user
      form_login:
        provider: users
        login_path: /login
        use_forward: false
        check_path: /login_check
        failure_path: null
        default_target_path: my_clients
      logout:
        path: /logout
        target: /login
      switch_user: true

  access_control:
    - { path: ^/login$, role: PUBLIC_ACCESS }
    - { path: ^/resetting, role: PUBLIC_ACCESS }
    - { path: ^/.*, role: [ ROLE_ADMIN, ROLE_SONATA_ADMIN ] }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, SONATA ]

    SONATA:
      - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are not using acl then this line must be uncommented
      - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT
  password_hashers:
    legacy:
      algorithm: sha512

    Symfony\Component\Security\Core\User\UserInterface:
      algorithm: auto
      migrate_from:
        - legacy
