sonata_user:
  security_acl: false
  manager_type: orm # can be orm or mongodb
  class:
    user: App\Entity\User
  impersonating:
    route: sonata_admin_dashboard
  resetting:
    email:
      address: sonata@localhost
      sender_name: Sonata Admin
