webpack_encore:
  output_path: "%kernel.project_dir%/public/_assets/js"
  script_attributes:
    defer: true
  preload: true

framework:
  assets:
    json_manifest_path: '%kernel.project_dir%/public/_assets/js/manifest.json'
